package me.Jonathon594.Mythria.Enum;

public enum Alignment {
    MELEE, ARCHERY, THIEVERY, CRAFTMANSHIP, CONSTRUCTION, FORTIFICATION, ENGINEERING, EXPLORATION, AGILITY, ARCANE, FORGING, MARITIME, COOKING, FISHING, GATHERING, FARMING, ALCHEMY, DEMOLITION, MINING, MARTIALARTS, MEDICAL, SURVIVAL, ARCANERY
}
