package me.Jonathon594.Mythria.Enum;

public enum AttributeFlag {
    DODGE, JUMP, FIREMAKING1, COOKING1, SOFTLANDING, WALLJUMP1, WALLJUMP2, ENLIGHTENMENT, PLANT_MAGIC, ICE_MAGIC, SAND_MAGIC, METAL_MAGIC, BASIC_SMITHING, ADVANCED_SMITHING, SOPHISTICATED_SMITHING, SUPERIOR_SMITHING, MASTERLY_SMITHING, ARTISAN_SMITHING, CARPENTRY, AXE_MASTERY, AXE_RAGE, AXE_SMASH, CRITICAL_AXE, FATAL_AXE, LEGENDARY_AXE, CRITICAL_SWORD, SWORD_MASTERY, FATAL_SWORD, DECAPICATE, STAGGER, FORTIFY, SHIELD_BASH, STAGGER_2, SHIELD_DISARM, SHIELD_CHARGE, SHIELD_ATTACKING, PARRY, COUNTERSTRIKE, FIST_TRAINING_1, DAZING_PUNCH, CRITICAL_FIST, DISARM, PRESSURE_POINT, CARDIAC_PUNCH, DEFLECT, DAGGER_SKILL_1, CRITICAL_DAGGER, DAGGER_SKILL_2, DAGGER_SKILL_3, FATAL_DAGGER, THROAT_SLICE, SKILLSHOT_1, ARROW_STUN, SKILLSHOT_2, ARROW_BLIND, ARROW_WEAKEN, ARROW_EXECUTE, PICKPICKET, WAND_CRAFTING, HAMMER_MASTERY, HAMMER_STAGGER, HAMMER_CONCUSSION, HAMMER_MASTERY_2, HAMMER_BREAK, SAVAGE_HAMMER, SMELTING

}
