package me.Jonathon594.Mythria.Enum;

public enum HealthConditionTree {
    BROKEN_LEFT_ANKLE, BROKEN_RIGHT_ANKLE, SKULL, RIGHT_ARM, LEFT_ARM, RIBS, PARASITES, SPRAIN_LEFT_ANKLE, SPRAIN_RIGHT_ANKLE, STOMACH_VIRUS, HYPOTHERMIA

}
