package me.Jonathon594.Mythria.Enum;

public enum MythicSkills {
    AGILITY, AXES, SWORDS, UNARMED, ARCHERY, ARCANERY, CRAFTING, STONECRAFT, SMITHING, ENGINEERING, ALCHEMY, MINING, MEDICAL, THIEVERY, FISHING, FARMING, WORSHIP, COOKING, GATHERING, FIREMAKING, BLOCK, SAILING, DAGGERS, PSIONICS, MYSTICISM, STRENGTH, CONCENTRATION, ENLIGHTENEMENT, WATER, COSMIC, EARTH, WIND, LIGHTNING, FIRE
}