package me.Jonathon594.Mythria.GUI;

public enum MythriaGui {
    MYTHRIA_MENU_GUI, MYTHRIA_PROFILE_CREATION_GUI, MYTHRIA_SHOW_PROFILE_GUI, MYTHRIA_SHOW_TRADESKILLS_GUI, MYTHRIA_SHOW_LIFESKILLS_GUI,
    MYTHRIA_SHOW_COMBATSKILLS_GUI, MYTHRIA_OPEN_CAMPFIRE_GUI, MYTHRIA_SKILL_BINDINGS_GUI, MYTHRIA_INVENTORY_GUI, MYTHRIA_SHOW_MAGICSKILLS_GUI,
    MYTHRIA_OPEN_CAMPFIRE_IMPROVED_GUI, MYTHRIA_EXPERIMENT_GUI, MYTHRIA_SHOW_PERSONALITIES_GUI, MYTHRIA_CUSTOM_CRAFTING_GUI, MYTHRIA_SMALL_VESSEL_GUI,
    MYTHRIA_PITKILN_GUI, MYTHRIA_FURNACE_GUI, MYTHRIA_SMALL_VESSEL_LIQUID_GUI, ANVIL_GUI, SAWHORSE_GUI, MYTHRIA_SHOW_ATTRIBUTE_GUI
}
